name: python-sdk

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Alith node SDK test
        run: python3 -m pip install alith
      - uses: PyO3/maturin-action@v1
        with:
          working-directory: "sdks/python"
          command: sdist
          args: -o dist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-${{ github.run_id }}
          path: sdks/python/dist

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64, aarch64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          working-directory: "sdks/python"
          command: build
          args: --release -o dist --find-interpreter
        env:
          # Workaround ring 0.17 build issue
          CFLAGS_aarch64_unknown_linux_gnu: "-D__ARM_ARCH=8"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.target }}-${{ github.run_id }}
          path: sdks/python/dist

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          working-directory: "sdks/python"
          command: build
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ github.run_id }}
          path: sdks/python/dist

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          working-directory: "sdks/python"
          command: build
          target: universal2-apple-darwin
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ github.run_id }}
          path: sdks/python/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'"
    permissions:
      contents: read
      id-token: write
    needs: [ macos, linux, windows ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-linux-x86_64-${{ github.run_id }}
          path: sdks/python/dist
      - uses: actions/download-artifact@v4
        with:
          name: wheels-linux-aarch64-${{ github.run_id }}
          path: sdks/python/dist
      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows-${{ github.run_id }}
          path: sdks/python/dist
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macos-${{ github.run_id }}
          path: sdks/python/dist
      - name: Publish to PyPI
        # The issue https://github.com/pypa/gh-action-pypi-publish/issues/310 has not tagged a release yet
        # Use the commit hash to get the temporary fix
        uses: pypa/gh-action-pypi-publish@cbd6d01d855e02aab0908c7709d5c0ddc88c617a
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          packages-dir: sdks/python/dist
